### ISSUE TITLE
Scaffold is not working correctly

### ISSUE THREAD

**Issue by Pan4ur** [PrismarineJS/mineflayer-pathfinder#232]
![ezgif-7-a06f96c1a9](https://user-images.githubusercontent.com/82473048/147915416-0a823dc4-ec33-4f5a-bd40-14047132eb48.gif)

**Comment by rom1504** [comment]
What server ?

**Comment by Pan4ur** [comment]
2b2t.dev

**Comment by IceTank** [comment]
This is due to anti-cheat + lag + latency. Mineflayer does not at the moment place blocks in the world unless they are updated by the server when placing blocks. So the bot sends a block place packet -> then falls back down into the block again. The server can ether 1. Refuse the block placement (happens here), or 2. Teleport the bot to above the block and place the block in the world. This can be fixed at some point by making an update to mineflayer. But none is working one that at the moment. You can also disable the ability for the bot the build 1x1 towers. This should for the most part fix the bot not getting anywhere. You can try an experimental fix by adding this line `bot.world.setBlockStateId(refBlock.position.offset(placingBlock.dx, placingBlock.dy, placingBlock.dz), 1)` right after this line here https://github.com/PrismarineJS/mineflayer-pathfinder/blob/5b26a7b2c77b4aec714399dcc6650d62ae05d457/index.js#L436

**Comment by Pan4ur** [comment]
Thanks, but the bot still can't climb
